server:
  port: 8082
spring:
  # Spring JPA
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:ppdb

  h2.console.enabled: true
  jpa:
    database: H2

    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${sso.url}/auth/realms/${sso.realm}/protocol/openid-connect/certs

  mail:
    host: localhost
    port: 8225
    username: pp-mail-user
    password: pp-mail-password

app:
  mail:
    from: "bot@test.de"
    reply-to: "testleitung@test.de"
  db:
    postgres:
      url: jdbc:postgresql://localhost:5432/praktikumsplaner
      username: db-backend-user
      password: db-backend-password

# Define the local keycloak realm here
# Define the local keycloak configuration here
# Deduplication-only property
sso:
  url: http://keycloak:8100
  realm: praktikumsplaner
  clientid: praktikumsplaner

refarch:
  security:
    logging-mode: all
