// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateMeldezeitraum: typeof import('./src/components/Meldezeitraeume/CreateMeldezeitraum.vue')['default']
    DatePicker: typeof import('./src/components/common/DatePicker.vue')['default']
    DatetimeInput: typeof import('./src/components/common/DatetimeInput.vue')['default']
    ExcelImportNWK: typeof import('./src/components/ExcelImportNWK.vue')['default']
    MeldungOertlAusbilder: typeof import('./src/components/MeldungPraktikumsstelle/MeldungOertlAusbilder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheSnackbar: typeof import('./src/components/TheSnackbar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VFadeTransition: typeof import('vuetify/lib')['VFadeTransition']
    VFileInput: typeof import('vuetify/lib')['VFileInput']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    YesNoDialog: typeof import('./src/components/common/YesNoDialog.vue')['default']
    ZeitraumPicker: typeof import('./src/components/Meldezeitraeume/ZeitraumPicker.vue')['default']
  }
}
