app:
  backend-service: <BACKEND_OPENSHIFT_SERVIE_NAME_BACKEND>
  frontend-service: <YOUR_OPENSHIFT_PROD_SERVICENAME>

spring:

  # Define the keycloak productive realm here
  realm: muenchen.de

  # spring cloud gateway config
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: false
      globalcors:
        corsConfigurations:
          # The cors configuration to allow frontend developers cross origin request via this api gateway
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://127.0.0.1:8081"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: sso
          uri: https://sso.muenchen.de/
          predicates:
            - Path=/api/sso/userinfo
          filters:
            - RewritePath=/api/sso/userinfo, /auth/realms/${spring.realm}/protocol/openid-connect/userinfo
        - id: backend
          uri: http://${app.backend-service}:8080/
          predicates:
            - Path=/api/aa-a-backend-service/**
          filters:
            - RewritePath=/api/aa-a-backend-service/(?<urlsegments>.*), /$\{urlsegments}
            - RemoveResponseHeader=WWW-Authenticate
      default-filters:
        - RemoveResponseHeader=Expires
        - RemoveRequestHeader=cookie
        - RemoveRequestHeader=x-xsrf-token
        - TokenRelay=

  # security config
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://sso.muenchen.de/auth/realms/${spring.realm}
        registration:
          keycloak:
            client-id: aa-a
            client-secret: 0b67133e-f4e0-42f6-b05f-7b51175969e8

  mvc:
    log-request-details: false

hazelcast:
  openshift-service-name: ${app.frontend-service}
