app:
  backend-service: <BACKEND_OPENSHIFT_SERVIE_NAME_BACKEND>
  frontend-service: <YOUR_OPENSHIFT_PROD_SERVICENAME>

spring:
  # spring cloud gateway config
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: false
      globalcors:
        corsConfigurations:
          # The cors configuration to allow frontend developers cross origin request via this api gateway
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://127.0.0.1:8081"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - RemoveResponseHeader=Expires
        - RemoveRequestHeader=cookie
        - RemoveRequestHeader=x-xsrf-token
        - TokenRelay=

  mvc:
    log-request-details: false

hazelcast:
  openshift-service-name: ${app.frontend-service}
