ALTER TABLE AUSBILDUNGSPRAKTIKUMSSTELLE ADD COLUMN meldezeitraumID varchar(36) not null;
ALTER TABLE STUDIUMSPRAKTIKUMSSTELLE ADD COLUMN meldezeitraumID varchar(36) not null;
ALTER TABLE AUSBILDUNGSPRAKTIKUMSSTELLE ADD FOREIGN KEY (meldezeitraumID) REFERENCES MELDEZEITRAUM (id);
ALTER TABLE STUDIUMSPRAKTIKUMSSTELLE ADD FOREIGN KEY (meldezeitraumID) REFERENCES MELDEZEITRAUM (id);