name: praktikumsplaner
services:
  pp-frontend:
    container_name: frontend
    image: itatm/praktikumsplaner-frontend:latest
    depends_on:
      - keycloak
    ports:
      - "8080:8082"
    profiles:
      - frontend
    pull_policy: always
    env_file:
      - local-docker-frontend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  pp-backend:
    container_name: backend
    image: itatm/praktikumsplaner-backend:latest
    ports:
      - "39146:39146"
    pull_policy: always
    env_file:
      - local-docker-backend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  # Keycloak (SSO)
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    command:
      - start-dev --http-relative-path /auth
    depends_on:
      - postgres-keycloak
    ports:
      - 8100:8080
    env_file:
      - local-keycloak.env
    networks:
      - keycloak

  init-keycloak:
    image: klg71/keycloakmigration
    depends_on:
      - keycloak
    env_file:
      - local-docker-keycloak.env
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: change_me
      BASEURL: http://keycloak:8080/auth # uses internal docker network to access the keycloak via its back channel port
      WAIT_FOR_KEYCLOAK: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
    volumes:
      - './keycloak/migration:/migration'
    networks:
      - keycloak

  postgres-keycloak:
    image: postgres:13.2
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak-user
      POSTGRES_PASSWORD: keycloak-secret
    networks:
      - keycloak
      - dbs

networks:
  internal:
  keycloak:
  dbs: