name: praktikumsplaner
services:
  pp-frontend:
    container_name: frontend
    image: itatm/praktikumsplaner-frontend:latest
    depends_on:
      - keycloak
    ports:
      - "8080:8082"
    profiles:
      - frontend
      - full
    pull_policy: always
    env_file:
      - local-docker-frontend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  pp-backend:
    container_name: backend
    image: itatm/praktikumsplaner-backend:latest
    ports:
      - "39146:39146"
    profiles:
      - backend
      - full
    pull_policy: always
    env_file:
      - local-docker-backend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  postgres-backend:
    image: postgres:16.4
    container_name: postgres-backend
    environment:
      POSTGRES_DB: praktikumsplaner
      POSTGRES_USER: db-backend-user
      POSTGRES_PASSWORD: db-backend-password
    ports:
      - "5432:5432"
    networks:
      - internal
      - dbs

  # Keycloak (SSO)
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    command:
      - start-dev --http-relative-path /auth
    depends_on:
      - postgres-keycloak
    ports:
      - 8100:8080
    env_file:
      - local-keycloak.env
    networks:
      - keycloak

  init-keycloak:
    image: klg71/keycloakmigration
    depends_on:
      - keycloak
    env_file:
      - local-docker-keycloak.env
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: change_me
      BASEURL: http://keycloak:8080/auth # uses internal docker network to access the keycloak via its back channel port
      WAIT_FOR_KEYCLOAK: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
    volumes:
      - './keycloak/migration:/migration'
    networks:
      - keycloak

  postgres-keycloak:
    image: postgres:16.4
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak-user
      POSTGRES_PASSWORD: keycloak-secret
    networks:
      - keycloak
      - dbs

  ## Tools

  postgres-pg-admin:
    image: dpage/pgadmin4:7.7
    container_name: postgres-pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a.de
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8101:80
    networks:
      - dbs

  mail-maildev:
    image: maildev/maildev
    ports:
      - "8180:1080"
      - "8125:1025"
    environment:
      MAILDEV_INCOMING_USER: pp-mail-user
      MAILDEV_INCOMING_PASS: pp-mail-password

  mail-mailpit:
    image: axllent/mailpit
    ports:
      - "8280:8025"
      - "8225:1025"
    environment:
      MP_SMTP_AUTH: "pp-mail-user:pp-mail-password"
      MP_SMTP_AUTH_ALLOW_INSECURE: true

networks:
  internal:
  keycloak:
  dbs: