name: praktikumsplaner
services:
  pp-frontend:
    container_name: frontend
    image: ghcr.io/it-at-m/praktikumsplaner/praktikumsplaner-frontend:latest@sha256:f4ce85ef47345fe0c7286bc90ebdc0c6caa68bc74fbb9190ec46ec43ab81853d
    depends_on:
      init-keycloak:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    profiles:
      - frontend
      - full
    pull_policy: always
    env_file:
      - local-docker-frontend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  pp-backend:
    container_name: backend
    image: ghcr.io/it-at-m/praktikumsplaner/praktikumsplaner-backend:latest@sha256:4c6c88de9b2906e0930f37bc0ac8d5666a8c6f3013442af81b4cb9490f8a9089
    ports:
      - "8082:8082"
    profiles:
      - backend
      - full
    pull_policy: always
    env_file:
      - local-docker-backend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  refarch-gateway:
    image: ghcr.io/it-at-m/refarch/refarch-gateway:1.7.0@sha256:3f82ab83c212ca53c9c2b606cfe29291f21525eac86fece215d0e1c6ca51273f
    depends_on:
      init-keycloak:
        condition: service_completed_successfully
    ports:
      - "8083:8080"
    environment:
      - ALLOWED_ORIGINS_PUBLIC=http://localhost:*
      - ALLOWED_ORIGINS_CLIENTS=http://localhost:*
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID=sso
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI=http://keycloak:8100/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0=Path=/api/sso/userinfo
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_FILTERS_0=RewritePath=/api/sso/userinfo, /auth/realms/praktikumsplaner/protocol/openid-connect/userinfo
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_ID=backend
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI=http://host.docker.internal:8082/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_PREDICATES_0=Path=/api/backend-service/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_FILTERS_0=RewritePath=/api/backend-service/(?<urlsegments>.*), /$\{urlsegments}
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_ID=frontend
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_URI=http://host.docker.internal:8081/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_PREDICATES_0=Path=/**
      - SPRING_PROFILES_ACTIVE=hazelcast-local
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8100/auth/realms/praktikumsplaner
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SSO_ISSUERURI=$${spring.security.oauth2.resourceserver.jwt.issuer-uri}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_PROVIDER=sso
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTID=praktikumsplaner
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTSECRET=top-secret
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE=profile, openid, roles
    networks:
      - keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck: &healthcheck
      test: [ "CMD-SHELL", "curl http://localhost:8080/actuator/health/liveness" ]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s
    security_opt: &security_settings
      - no-new-privileges:true

  postgres-backend:
    image: postgres:17.6@sha256:00bc86618629af00d2937fdc5a5d63db3ff8450acf52f0636ec813c7f4902929
    container_name: postgres-backend
    environment:
      POSTGRES_DB: praktikumsplaner
      POSTGRES_USER: db-backend-user
      POSTGRES_PASSWORD: db-backend-password
    ports:
      - "5432:5432"
    networks:
      - internal
      - dbs

  # Keycloak (SSO)
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0@sha256:5f3fb534cde6bf006d79f5912473e5d2c828c707cdfc52e16972803aca9d43dd
    container_name: keycloak
    command:
      - start-dev
    depends_on:
      - postgres-keycloak
    ports:
      - "8100:8100"
    env_file:
      - local-keycloak.env
    networks:
      - keycloak

  init-keycloak:
    image: klg71/keycloakmigration:0.2.124@sha256:8da8f5321805d4f734116931f2824d0f89173adbbd317160fa5713479b75acc7
    depends_on:
      - keycloak
    env_file:
      - local-docker-keycloak.env
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: change_me
      BASEURL: http://keycloak:8100/auth # uses internal docker network to access the keycloak via its back channel port
      WAIT_FOR_KEYCLOAK: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
    volumes:
      - './keycloak/migration:/migration'
    networks:
      - keycloak

  postgres-keycloak:
    image: postgres:17.6@sha256:00bc86618629af00d2937fdc5a5d63db3ff8450acf52f0636ec813c7f4902929
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak-user
      POSTGRES_PASSWORD: keycloak-secret
    networks:
      - keycloak
      - dbs

  ## Tools

  postgres-pg-admin:
    image: dpage/pgadmin4:9.11@sha256:50700ac17936d0227f9e3e4bb086a91efb67064debc4b4737c35545bf1564088
    container_name: postgres-pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a.de
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8101:80"
    networks:
      - dbs

  mail-maildev:
    image: maildev/maildev@sha256:180ef51f65eefebb0e7122d8308813c1fd7bff164bc440ce5a3c2feee167a810
    ports:
      - "8180:1080"
      - "8125:1025"
    environment:
      MAILDEV_INCOMING_USER: pp-mail-user
      MAILDEV_INCOMING_PASS: pp-mail-password

  mail-mailpit:
    image: axllent/mailpit@sha256:c5a6d0ba4d08187f70f305471da5fd9ad424fdfc2f25a2308226a786335dfa9f
    ports:
      - "8280:8025"
      - "8225:1025"
    environment:
      MP_SMTP_AUTH: "pp-mail-user:pp-mail-password"
      MP_SMTP_AUTH_ALLOW_INSECURE: true

networks:
  internal:
  keycloak:
  dbs: