name: praktikumsplaner
services:
  #
  # Praktikumsplaner Services
  #
  pp-frontend:
    image: ghcr.io/it-at-m/praktikumsplaner/praktikumsplaner-frontend:latest@sha256:f4ce85ef47345fe0c7286bc90ebdc0c6caa68bc74fbb9190ec46ec43ab81853d
    depends_on:
      init-keycloak:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    profiles:
      - frontend
      - full
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  pp-backend:
    image: ghcr.io/it-at-m/praktikumsplaner/praktikumsplaner-backend:latest@sha256:e2b3aea1693b53e2315469738fe30deb6949177b720164213f219ae4631f18ef
    ports:
      - "8082:8082"
    profiles:
      - backend
      - full
    pull_policy: always
    environment:
      - APP_DB_POSTGRES_URL=jdbc:postgresql://postgres:5432/praktikumsplaner
      - SPRING_PROFILES_ACTIVE=local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - keycloak

  #
  # Database
  #
  postgres:
    image: postgres:17.6@sha256:00bc86618629af00d2937fdc5a5d63db3ff8450acf52f0636ec813c7f4902929
    environment:
      POSTGRES_DB: praktikumsplaner
      POSTGRES_USER: db-backend-user
      POSTGRES_PASSWORD: db-backend-password
    ports:
      - "5432:5432"
    networks:
      - internal
      - dbs
    healthcheck: &healthcheck
      test: ["CMD-SHELL", "pg_isready -d postgres -U admin"]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s
    security_opt: &security_settings
      - no-new-privileges:true

  pg-admin:
    image: dpage/pgadmin4:9.12.0@sha256:10137f33be7ed61e47f56004493710cb5b80ba7fb0ca01758855e242f1f284a7
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_REPLACE_SERVERS_ON_STARTUP=True
      - PGADMIN_DISABLE_POSTFIX=True
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED=False
    ports:
      - "5050:5050"
    networks:
      - dbs
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "-O", "-", "http://localhost:5050/misc/ping"]
    security_opt: *security_settings
    volumes:
      - './pgadmin/servers.json:/pgadmin4/servers.json:ro'
      - './pgadmin/preferences.json:/pgadmin4/preferences.json:ro'
      - './pgadmin/pgpass:/tmp/pgpass.mounted:ro'
      - './pgadmin/data:/tmp/data'
    entrypoint: >
      /bin/sh -c "
        cp -f /tmp/pgpass.mounted /tmp/pgpass;
        chmod 600 /tmp/pgpass;
        /entrypoint.sh
      "

  #
  # Keycloak
  #
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5@sha256:4883630ef9db14031cde3e60700c9a9a8eaf1b5c24db1589d6a2d43de38ba2a9
    command:
      - start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_PORT=8100
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - "8100:8100"
    networks:
      - keycloak
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then exit 0;else exit 1;fi;"]
    security_opt: *security_settings

  init-keycloak:
    image: klg71/keycloakmigration:0.2.125@sha256:a326d3e50e2a35b70a3cf3a5d33288af9bcba27fef89146a2107622583e34231
    depends_on:
      - keycloak
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      BASEURL: http://keycloak:8100/auth
      WAIT_FOR_KEYCLOAK: 'true'
      FAIL_ON_UNDEFINED_VARIABLES: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
      SSO_REALM: praktikumsplaner
      SSO_CLIENT_ID: praktikumsplaner
      SSO_CLIENT_SECRET: top-secret
    volumes:
      - './keycloak/migration:/migration'
    networks:
      - keycloak
    security_opt: *security_settings

  #
  # Gateway
  #
  refarch-gateway:
    image: ghcr.io/it-at-m/refarch/refarch-gateway:1.7.0@sha256:3f82ab83c212ca53c9c2b606cfe29291f21525eac86fece215d0e1c6ca51273f
    depends_on:
      init-keycloak:
        condition: service_completed_successfully
    ports:
      - "8083:8080"
    environment:
      - ALLOWED_ORIGINS_PUBLIC=http://localhost:*
      - ALLOWED_ORIGINS_CLIENTS=http://localhost:*
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID=sso
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI=http://keycloak:8100/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0=Path=/api/sso/userinfo
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_FILTERS_0=RewritePath=/api/sso/userinfo, /auth/realms/praktikumsplaner/protocol/openid-connect/userinfo
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_ID=backend
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI=http://host.docker.internal:8082/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_PREDICATES_0=Path=/api/backend-service/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_FILTERS_0=RewritePath=/api/backend-service/(?<urlsegments>.*), /$\{urlsegments}
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_ID=frontend
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_URI=http://host.docker.internal:8081/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_PREDICATES_0=Path=/**
      - SPRING_PROFILES_ACTIVE=hazelcast-local
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8100/auth/realms/praktikumsplaner
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SSO_ISSUERURI=$${spring.security.oauth2.resourceserver.jwt.issuer-uri}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_PROVIDER=sso
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTID=praktikumsplaner
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTSECRET=top-secret
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE=profile, openid, roles
    networks:
      - keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL", "curl http://localhost:8080/actuator/health/liveness" ]
    security_opt: *security_settings

  #
  # Mail
  #
  mail-mailpit:
    image: axllent/mailpit:v1.29.2@sha256:030f06031ce5c60913ac9363da1ab0d4be6fd2a78147dd0e1ca0fcac665d6b34
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH: "pp-mail-user:pp-mail-password"
      MP_SMTP_AUTH_ALLOW_INSECURE: true

networks:
  internal:
  keycloak:
  dbs:
