export const Studiensemester = [
  {
    name: "1. Semester",
    value: "SEMESTER1",
    zeitraumBSC: "Februar - Mitte März",
    zeitraumBWI: "01.09 - 28.02",
    zeitraumVI: "Februar - Mitte März",
    zeitraumLLB: "01.09 - 28.02",
    zeitraumPUMA: "01.09 - 28.02",
    zeitraumQE3: "Nicht in ausgewähltem Semester verfügbar",
  },
  {
    name: "2. Semester",
    value: "SEMESTER2",
    zeitraumBSC: "Ende Juli - Ende September",
    zeitraumBWI: "01.03 - 01.09",
    zeitraumVI: "Nicht in ausgewähltem Semester verfügbar",
    zeitraumLLB: "01.03 - 31.08",
    zeitraumPUMA: "01.03 - 31.08",
    zeitraumQE3: "Mai - September",
  },
  {
    name: "3. Semester",
    value: "SEMESTER3",
    zeitraumBSC: "Februar - Mitte März",
    zeitraumBWI: "01.09 - 28.02",
    zeitraumVI: "Oktober - März",
    zeitraumLLB: "01.09 - 28.02",
    zeitraumPUMA: "01.09 - 28.02",
    zeitraumQE3: "Dezember - April",
  },
  {
    name: "4. Semester",
    value: "SEMESTER4",
    zeitraumBSC: "Juli - Mitte März (Praxissemester)",
    zeitraumBWI: "01.03 - 01.09",
    zeitraumVI: "Nicht in ausgewähltem Semester verfügbar",
    zeitraumLLB: "01.03 - 31.08",
    zeitraumPUMA: "01.03 - 31.08",
    zeitraumQE3: "Nicht in ausgewähltem Semester verfügbar",
  },
  {
    name: "5. Semester",
    value: "SEMESTER5",
    zeitraumBSC: "Juli - Mitte März (Praxissemester)",
    zeitraumBWI: "01.09 - 30.06",
    zeitraumVI: "August - Ende September",
    zeitraumLLB: "01.09 - 30.06",
    zeitraumPUMA: "01.09 - 31.07",
    zeitraumQE3: "August - Dezember",
  },
  {
    name: "6. Semester",
    value: "SEMESTER6",
    zeitraumBSC: "Ende Juli - Ende September",
    zeitraumBWI: "01.09 - 30.06",
    zeitraumVI: "Februar",
    zeitraumLLB: "01.09 - 30.06",
    zeitraumPUMA: "01.09 - 31.07",
    zeitraumQE3: "Nicht in ausgewähltem Semester verfügbar",
  },
] as const;
export function valueToNameStudiensemester(value: string): string {
  return Studiensemester.find((s) => s.value === value)?.name || "";
}
