name: build frontend

on:
  push:
    branches-ignore:
      - 'dev'
      - 'main'
    paths:
      - 'praktikumsplaner-frontend/**'
  pull_request:
    types: [opened, reopened]

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "./praktikumsplaner-frontend/package-lock.json"
      - name: Install dependencies
        run: npm --prefix ./praktikumsplaner-frontend ci
        shell: bash
      - name: Run lint
        run: npm run --prefix  ./praktikumsplaner-frontend lint
        shell: bash
      - name: Run test
        run: npm run  --prefix ./praktikumsplaner-frontend test
        shell: bash
      - name: Run build
        run: npm run  --prefix ./praktikumsplaner-frontend build
        shell: bash
