name: build backend-image

on:
  push:
    branches:
      - 'dev'
      - 'main'
    paths:
      - 'praktikumsplaner-backend/**'

jobs:
  build-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --no-transfer-progress -f praktikumsplaner-backend/pom.xml verify

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./praktikumsplaner-backend
          push: true
          tags: itatm/praktikumsplaner-backend:latest
