name: build frontend

on:
  push:
    branches-ignore:
      - 'dev'
      - 'main'
    paths:
      - 'praktikumsplaner-frontend/**'
  pull_request:
    types: [opened, reopened]

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22.22.0
          cache: "npm"
          cache-dependency-path: "./praktikumsplaner-frontend/package-lock.json"
      - name: Install dependencies
        run: npm --prefix ./praktikumsplaner-frontend ci
        shell: bash
      - name: Run lint
        run: npm run --prefix  ./praktikumsplaner-frontend lint
        shell: bash
      - name: Run test
        run: npm run  --prefix ./praktikumsplaner-frontend test
        shell: bash
      - name: Run build
        run: npm run  --prefix ./praktikumsplaner-frontend build
        shell: bash
