# Workflow for building NPM/Maven projects and Docker images
name: build

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TZ: Europe/Berlin
    strategy:
      fail-fast: false
      matrix:
        include: # Add or modify paths according to your project structure
          - app-path: praktikumsplaner-backend
          - app-path: praktikumsplaner-frontend

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
      - id: node # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
        with:
          app-path: ${{ matrix.app-path }}
          node-version: "24"
      - id: maven # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
        with:
          app-path: ${{ matrix.app-path }}
          java-version: "21"
      - if: github.ref == 'refs/heads/main'
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
        with:
          path: ${{ matrix.app-path }}
          image-name: ${{ matrix.app-path }}
          artifact-name: ${{ join(steps.*.outputs.artifact-name) }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=raw,value=dev
