name: Release Docs

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  release-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: "./doc/package-lock.json"
      - run: npm install
      - run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/docs/.vitepress/dist