name: release services

on:
  workflow_call:
    inputs:
      release-version:
        description: 'Services release version'
        type: string
        required: true

jobs:
  backend-build-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          cache: "maven"
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --no-transfer-progress -f praktikumsplaner-backend/pom.xml verify

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./praktikumsplaner-backend
          push: true
          tags: itatm/praktikumsplaner-backend:latest,itatm/praktikumsplaner-backend:${{ inputs.release-version }}

  frontend-build-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          cache: "maven"
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --no-transfer-progress -f praktikumsplaner-frontend/pom.xml verify

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./praktikumsplaner-frontend
          push: true
          tags: itatm/praktikumsplaner-frontend:latest,itatm/praktikumsplaner-frontend:${{ inputs.release-version }}