# Workflow for running security scan using Trivy
name: trivy

on:
  pull_request:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required to upload SARIF results to the GitHub Security tab
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@8743ef6c6599717280e242bc6e2c326b43518c0c
        with:
          path: './praktikumsplaner-backend'
